### ISSUE TITLE
support for waveshare eink displays

### ISSUE THREAD

**Issue by uududde** [donbing/bitbot#59]
I really like your frame with the 5.7 inch setup at etsy... if it weren't for customs. 
  
Is there any chance the bitbot would also work with a Waveshare 5.65inch 7color e-Paper Module  or a 2.7inch e-Paper HAT (with red/black/white) in connection with a pi zero?

**Comment by donbing** [comment]
Thank-you :D The thicker metal on the [5.7" model](https://www.etsy.com/uk/listing/1179982941) looks and feels great, but they're a **real pain** to make. 

I've just tried the `2.7" red waveshare display`, and it's not working. I doubt any other Waveshares will ATM.

I have been planning on updating the Bitbot to use this driver -> [https://github.com/robweber/omni-epd](https://github.com/robweber/omni-epd), which does look like it would support the screen that you're talking about... I'll open up a branch for investigating it.

P.S. message me on Etsy saying what country you're in, I'll see if I can give you a discount code to cover customs. (special promo for first buyer of the 5.7" model)

**Comment by donbing** [comment]
Well, I had a quick try.. but getting the `2.7" Red Waveshare` working isn't going to be that easy.. the 5.7" would probably work better as the resolution is already supported.

![20220224_230603](https://user-images.githubusercontent.com/413860/155622637-cc54d1dc-2ea1-480e-9bc2-d6bd181346b6.jpg)

**Comment by uududde** [comment]
I just tried the Waveshare 5.65inch 7color eink display. After installing manually via commandline (the image version didn't work and would not connect to my wifi) I rebooted and started the script which resulted in: 
```
pi@raspberrypi:~/bitbot $ python3 -m run
Matplotlib is building the font cache; this may take a moment.
2022-02-25 19:12:24,608 [INFO] root: load_config_ini: <Bitbot config files:/home/pi/bitbot>
2022-02-25 19:12:24,666 [CRITICAL] root: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/bitbot/run.py", line 24, in <module>
    app = BitBot(config, config_files)
  File "/home/pi/bitbot/src/bitbot.py", line 27, in __init__
    self.display = display_picker(config)
  File "/home/pi/bitbot/src/kinky.py", line 28, in picker
    return Inker(config)
  File "/home/pi/bitbot/src/kinky.py", line 73, in __init__
    self.display = auto()
  File "/home/pi/.local/lib/python3.9/site-packages/inky/auto.py", line 66, in auto
    raise RuntimeError("No EEPROM detected! You must manually initialise your Inky board.")
RuntimeError: No EEPROM detected! You must manually initialise your Inky board.
```
luckily tomorrow my inky 5.7 color eink arrives =)

**Comment by donbing** [comment]
yeah, the current driver wont work with the Waveshares at all. 

I've opened up a branch to get the omni-epd driver working, unfortunately it turns out that omni-epd itself [has a critical bug](https://github.com/robweber/omni-epd/issues/58) that was preventing me from moving forwards. It looks like this may be fixed now, so I might have the Bitbot working on Waveshare displays soon.
